{
  "language": "java",
  "cache": {
    "directories": [
      "$HOME/.m2"
    ]
  },
  "install": [
    "sudo apt-get install phantomjs",
    "export PATH=$PATH:/tmp/casperjs/bin"
  ],
  "script": [
    "mvn clean install -Pqulice --batch-mode --errors"
  ]
}